import { Josefin_Sans, Caveat } from "next/font/google";

import "./globals.css";

const josefin = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
});
const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
});
export const metadata = {
  title: "Guillem RT",
  description: "Generated by Guillem",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${josefin.variable} ${caveat.variable} antialiased relative min-h-screen`}
      >
        <div className='fixed inset-0 -z-10 overflow-hidden'>
          <div className='absolute -left-20 -top-20 w-204 h-164 rounded-full bg-blue-100 opacity-30 blur-3xl animate-cloud1'></div>
          <div className='absolute -right-20 -top-20 w-180 h-180 rounded-full bg-blue-200 opacity-30 blur-3xl animate-cloud2'></div>
          <div className='absolute -left-20 -bottom-20 w-172 h-172 rounded-full bg-blue-300 opacity-30 blur-3xl animate-cloud3'></div>
          <div className='absolute -right-20 -bottom-20 w-196 h-196 rounded-full bg-blue-300 opacity-30 blur-3xl animate-cloud4'></div>
        </div>

        {children}
      </body>
    </html>
  );
}
